### ISSUE TITLE
Missing property "condition"

### ISSUE THREAD

**Issue by philbowers** [keesschollaart81/vscode-home-assistant#399]
It might just be something I haven't configured correctly yet. I just installed the VScode add-on in home assistant and, when looking through file tree, I had 4 error notifications pop-up in one of the files. 

Here's the issue I'm having: When the script states `- domain: switch` VScode throws error `Missing property "condition"`

```
script:
  pool_pump_on:
    alias: pool pump on
    sequence:
    - condition: state
      entity_id: binary_sensor.pool_pump_running
      state: 'off'
    - domain: switch 
      device_id: 59e8cf3f7b5c4d618bad2e57fd180af4
      entity_id: switch.zooz_z16_a000_id_a00a_switch_4
      type: turn_on

  pool_pump_off:
    alias: pool pump off
    sequence:
    - domain: switch 
      device_id: 5ac98b055646498cb818bb10042a8598
      entity_id: switch.zooz_z16_a000_id_a00a_switch_2
      type: turn_off
    - delay: "00:00:10"
    - domain: switch 
      device_id: 59e8cf3f7b5c4d618bad2e57fd180af4
      entity_id: switch.zooz_z16_a000_id_a00a_switch_4
      type: turn_off
    - service: notify.mobile_app_phils_note_10
      data:
        message: The pool pump is off

  polaris_pump_on:  
    alias: polaris pump on
    sequence:
    - condition: state
      entity_id: binary_sensor.pool_pump_running
      state: 'on'
    - condition: state
      entity_id: binary_sensor.polaris_pump_running
      state: 'off'
    - domain: switch 
      device_id: 5ac98b055646498cb818bb10042a8598
      entity_id: switch.zooz_z16_a000_id_a00a_switch_2
      type: turn_on
    - service: notify.mobile_app_phils_note_10
      data:
        message: Polaris pump is on
```
screen capture:
![miss_prop](https://user-images.githubusercontent.com/8340735/87866254-6c02a980-c94d-11ea-8d25-69c37000a846.png)

Visual Studio Code
Current version: 2.3.0

code-server: v3.4.0
 VS Code: v1.45.1
Commit: 69ad52907e8ea109345831d29da5425cb2a55047
Date: 2020-05-27T23:38:22Z

**Comment by frenck** [comment]
This is truly an interesting report. I can reproduce it, but the schema definition is there. I'm currently unsure why the language service doesn't pick it up.

**Comment by CineMAC-HA** [comment]
Hi Frenck and Phil,
that's exactly my problem. but also for other propertys. I had already written here ...
All the scripts running fine, only the message in the vsc. 

https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863/316

![image](https://user-images.githubusercontent.com/66432847/88518751-4599d980-cff1-11ea-8c4d-180a20eb0711.png)

**Comment by frenck** [comment]
@CineMAC-HA sorry, but that is not related to this issue and fixed in v1.8.0 of this extension already.

**Comment by CineMAC-HA** [comment]
Sorry for mistake from my side Frenck, I am a beginner with home assistant and vsc. But the problem is not fixed for me and i searching a solution.

**Comment by frenck** [comment]
Well this is the vscode extension, you are referring to the add-on, which is a different thing.
The add-on needs updating, however, that is currently blocked due to an incompatibility issue, which awaits a fix from upstream.

However, offtopic for this issue.

**Comment by frenck** [comment]
Found the issue with the report. Fixed in #427, staged for next release.
